[build]
target = "x86_64-pc-windows-gnullvm"
target-dir = "D:/temp_build/target"

[target.x86_64-pc-windows-gnullvm]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-Ld:/ai work/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnullvm/lib/self-contained",
    "-C", "link-arg=d:/ai work/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/self-contained/crt2.o",
]
